### ISSUE TITLE
Add LB service support for Slice VPN Gateways

### ISSUE THREAD

**Issue by pnavali** [kubeslice/worker-operator#287]
Add LB Service to VPN Gateways for private VPC support.

**Comment by mridulgain** [comment]
PRs

- kubeslice-worker  #316 
- kubeslice-controller  https://github.com/kubeslice/kubeslice-controller/pull/180

**Comment by mridulgain** [comment]
This has been included in [v1.2.0](https://github.com/kubeslice/worker-operator/releases/tag/v1.2.0)
