### ISSUE TITLE
Update developer guide

### ISSUE THREAD

**Issue by Rahul-D78** [kubeslice/worker-operator#305]
Currently the developer guide only has information about [Building and Installing kubeslice-worker](https://github.com/kubeslice/worker-operator/blob/master/developer_guide.md#building-and-installing-kubeslice-worker-in-a-local-kind-cluster) and how to run tests. It should also include: 
* Guidelines for submitting a pull request.
* Commit Message Guidelines like PR should have a description body and a proper commit prefix.
* Coding Rule section can include topics like following the [GoLang style guide](https://google.github.io/styleguide/go/), Unit tests and Integration tests as well as adding comments in the code.
* Commit prefix can be one of the type.
```
build: Changes that affect the build system or external dependencies (example scopes: Makefile, Dockerfile)
ci: Changes to our CI configuration files and scripts (example scopes: GitHub Action, JenkinsFile)
docs: Documentation only changes
feat: A new feature
fix: A bug fix
perf: A code change that improves performance
refactor: A code change that neither fixes a bug nor adds a feature
style: Changes that do not affect the meaning of the code (white-space, formatting, missing semi-colons, etc)
test: Adding missing tests or correcting existing tests
```

**Comment by narmidm** [comment]
@Rahul-D78 - recreate this with the issue with the bug template for better visibility.

**Comment by Rahul-D78** [comment]
Changes are already present - 
https://github.com/kubeslice/worker-operator/blob/master/CONTRIBUTING.md
