### ISSUE TITLE
Pod Disruption Budget for slice gateway pods

### ISSUE THREAD

**Issue by bharath-avesha** [kubeslice/worker-operator#308]
### 🔖 Feature description

Create and reconcile PodDisruptionBudget for slice gateway pods.

### 🎤 Pitch

We need this enhancement to avoid connectivity loss between clusters of a slice during disruptions. Atleast one pair of slice gateway pods should be present between a pair of clusters.

### ✌️ Solution

We should create PodDisruptionBudget objects for the slice gateway pods, and reconcile them periodically. 

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/kubeslice/worker-operator/blob/master/code_of_conduct.md)

**Comment by Bhargav-InfraCloud** [comment]
Hi, I want to give it a try, Can you please assign this to me?
/assign

**Comment by narmidm** [comment]
sure @Bhargav-InfraCloud

**Comment by Bhargav-InfraCloud** [comment]
##  Approach from a High-level
The reconciler should watch for `SliceGateway` objects if:
- **Created**: Create a PDB with
	- matchLabels with labels that match both slice gateway's deployments. Eg.
	  `"kubeslice.io/slice=water` &&
	  `kubeslice.io/slicegw=water-kind-kubeslice-worker-1-kind-kubeslice-worker-2`"
	- `minAvailable` = 1
	- labels will contain the SliceGateway's name to make it easy to delete PDB.
- **Updated**: There is nothing to change in PDB as the SliceGateway's name is expected to be the same even after the update.
- **Deleted**: Delete the matching PDB.

@narmidm @bharath-avesha If that looks reasonable, I need your opinion on the following.
1. Add the PDB logic in `SliceGwReconciler` that exists.
2. Create a new reconciler for creating PDB alone.
I don't think there is a great advantage to choosing one over the other. WDYT?
